package be.zwaldeck.killemall.entity.config;

public enum  AnimationType {
    FEET_IDLE,
    FEET_WALKING,
    FEET_RUNNING,
    FEET_STRAFE_LEFT,
    FEET_STRAFE_RIGHT,

    FLASHLIGHT_IDLE,
    FLASHLIGHT_MELEE,
    FLASHLIGHT_WALKING,

    HANDGUN_IDLE,
    HANDGUN_MELEE,
    HANDGUN_WALKING,
    HANDGUN_RELOAD,
    HANDGUN_SHOOTING,

    KNIFE_IDLE,
    KNIFE_MELEE,
    KNIFE_WALKING,

    RIFLE_IDLE,
    RIFLE_MELEE,
    RIFLE_WALKING,
    RIFLE_RELOAD,
    RIFLE_SHOOTING,

    SHOTGUN_IDLE,
    SHOTGUN_MELEE,
    SHOTGUN_WALKING,
    SHOTGUN_RELOAD,
    SHOTGUN_SHOOTING
}
